### ISSUE TITLE
pqn coefficients and glog lambda cant be applied to validation data sets

### ISSUE THREAD

**Issue by grlloyd** [computational-metabolomics/pmp#18]
I'd like to 'train' pqn and glog on one dataset, then use the values on a test/validation dataset

**Comment by andzajan** [comment]
Changes for PQN implemented in https://github.com/computational-metabolomics/pmp/pull/19.

**Comment by andzajan** [comment]
Funcionality to add fixed lambda value as glog transformation input implemented in https://github.com/computational-metabolomics/pmp/commit/bfef14280f23b8cbaad60e408e9563586471ad5e.

Function to calculate glog by using SSE optimisation: https://github.com/computational-metabolomics/pmp/commit/085029bde0167ab66dc67335c1e9aeaac28dd7b4
